# Site settings
title: Living Art
email: 278f8113e29510f4237d584e461ae999 #w.bligh@gmail.com
url: https://willbligh.github.com/livingart
description: "Living Art Productions showcases projects by Will Bligh."
keywords: "Bligh, Film, Theatre"
skills: "Innovative Theatre and Film Projects"
meta_author: Bligh Will

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formsubmit.co to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
# disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: d69806 #80B3FF
  primary-rgb: "214,152,6" #"128,179,255"
  secondary: 1e1f2b #FD6E8A
  secondary-dark: 0e0f14 #A2122F

# Footer settings
footer:
  copyright: Will Bligh
  location: Location
  social: Around the Web
  credits: More Info

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: youtube
    url: https://www.youtube.com/@livingartproductions
  - title: facebook
    url:
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket
#    url: http://bitbucket.org/jekyll
#  - title: github
#    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Queensland
  - line: Australia

# Credits content
credits: 'More information on the projects can be found at <a href="http://willbligh.com">Will Bligh</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
